import {
  Any,
  MoreThan,
  Equal,
  Not,
  MoreThanOrEqual,
  ArrayContainedBy,
  ArrayOverlap,
  IsNull,
  LessThan,
  LessThanOrEqual,
  Like,
  ILike,
  Between,
  In,
  ArrayContains,
} from 'typeorm'

export const FILTER_MAP = {
  not: Not,
  less_than: LessThan,
  less_than_or_equal_to: LessThanOrEqual,
  greater_than: MoreThan,
  greater_than_or_equal_to: MoreThanOrEqual,
  equal: Equal,
  like: Like,
  i_like: ILike,
  between: Between,
  in: In,
  any: Any,
  is_null: IsNull,
  array_contains: ArrayContains,
  array_contained_by: ArrayContainedBy,
  array_overlaps: ArrayOverlap,
}
